# Generated by Django 4.2.6 on 2023-10-12 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=100)),
                ('publisher_logo', models.ImageField(upload_to='publisher_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_book_name', models.CharField(blank=True, max_length=100)),
                ('en_book_name', models.CharField(blank=True, max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('translator', models.CharField(max_length=100)),
                ('book_photo', models.ImageField(upload_to='book_photo')),
                ('read_count', models.IntegerField(default=0)),
                ('reading_count', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('book_genre', models.ManyToManyField(to='Book.genre')),
                ('book_publisher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Book.publisher')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
                'db_table': 'Book',
            },
        ),
    ]
